### PR TITLE
[READY] add git to the awsutils img

### PR DESCRIPTION
**Pull request by egiffen**
## Description of PR

Add the git pkg to the awsutils img.

## Tests
Verify the img builds with the correct package.

### CODE REVIEW

**Review by sarcasticadmin — APPROVED** [review]
@egiffen nice looks good, go ahead and push it up!

**Comment by egiffen** [comment]
publish

**Comment by nwi-auto** [comment]
The following docker images: 
awsutils, helmsman-aws, magic-wormhole-mailbox, pki-validator
have been published on [Docker Hub](https://hub.docker.com/u/nebulaworks).

**Comment by sarcasticadmin** [comment]
:shipit: nice job @egiffen

**Pull request merged**
