### PR TITLE
[READY] - Remove local helm-diff drv and adding release.nix

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description of PR

Updating the helsman container to be leverage all upstream nixpkgs

## Previous Behavior
- Pinned the `helsman` container to specific nixpkg version
- Leverage local `helm-diff`

## New Behavior
- Leverage `helm-diff` from upstream nixpkgs
- `helmsman` container unpinned
- Leveraging of `release.nix` to have a predictable point in time for builds
- Removing old pins to nixpkgs

## Tests
Can build with both `release.nix`:

```
$ nix-build release.nix -A imgs.helmsman-aws
```

And `default.nix`:

```
$ nix-build -A imgs.helmsman-aws
```

Container was built in both cases and works as expected. Checking `helm and helmsman`:

```
bash-4.4# helmsman -v
Helmsman version: v3.6.11
bash-4.4# helm plugin list
NAME    VERSION DESCRIPTION                           
diff    3.1.3   Preview helm upgrade changes as a diff
```

Containers using `default.nix` are built successfully through `publish` command: https://github.com/Nebulaworks/nix-garage/pull/35#issuecomment-888454023

### CODE REVIEW

**Review by jshcmpbll — APPROVED** [review]
LGTM! 🚀

**Comment by sarcasticadmin** [comment]
publish

**Comment by sarcasticadmin** [comment]
Publish failed 😢  : https://github.com/Nebulaworks/nix-garage/runs/3175928079?check_suite_focus=true

```
Adding /nix/store/9hxb506q8285gckhdacr72qx3zlkxrl6-gzip-1.10
Packing layer...
Finished building layer 'awsutils'
building '/nix/store/8f5pdxk1jr3c7g0526m8yzfcbv318nii-runtime-deps.drv'...
building '/nix/store/rr7z4wsgndfdcr6ic9lz94ipj117m504-docker-image-awsutils.tar.gz.drv'...
Adding layer...
tar: Removing leading `/' from member names
Adding meta...
Cooking the image...
Finished.
/nix/store/hbqmiwillbddpzdjdl0v8y5h1xxy1bwx-docker-image-awsutils.tar.gz
time="2021-07-27T20:50:41Z" level=fatal msg="Error loading trust policy: open /etc/containers/policy.json: no such file or directory"
```

Looks like its due to `skopeo` needing `--insecure-policy`, similar to this:
https://github.com/NixOS/nixpkgs/blob/3b6c3bee9174dfe56fd0e586449457467abe7116/pkgs/build-support/docker/nix-prefetch-docker#L41

This seems to be related to some other issues that ran into similar behavior:

- https://github.com/containers/skopeo/issues/687#issuecomment-507619077
- https://github.com/containers/skopeo/issues/1315

**Comment by sarcasticadmin** [comment]
publish

**Comment by nwi-auto** [comment]
The following docker images:
awsutils, flasksample, helmsman-aws, magic-wormhole-mailbox, pki-validator
have been published on [Docker Hub](https://hub.docker.com/u/nebulaworks).

**Comment by sarcasticadmin** [comment]
✅  Confirmed that containers built and are operational:

`helmsman-aws`:

```
~ $ docker-run nebulaworks/helmsman-aws:vibjzpbdqxyfxppd37sy8sskbn9knd10 /bin/bash
bash-4.4# helm plugin list
NAME    VERSION DESCRIPTION                           
diff    3.1.3   Preview helm upgrade changes as a diff
bash-4.4# helmsman -v
Helmsman version: v3.6.11
bash-4.4# 
```

`aws-utils`
```
~ $ docker-run nebulaworks/awsutils:hbqmiwillbddpzdjdl0v8y5h1xxy1bwx /bin/bash
Unable to find image 'nebulaworks/awsutils:hbqmiwillbddpzdjdl0v8y5h1xxy1bwx' locally
hbqmiwillbddpzdjdl0v8y5h1xxy1bwx: Pulling from nebulaworks/awsutils
314dcf4093bf: Pull complete 
Digest: sha256:8d398b7567df2d6e1c737d3b97d149697b0e229c7ecbb81cf778ad02a74c9f3d
Status: Downloaded newer image for nebulaworks/awsutils:hbqmiwillbddpzdjdl0v8y5h1xxy1bwx
bash-4.4# aws --version
aws-cli/1.19.88 Python/3.8.9 Linux/4.9.184-linuxkit botocore/1.20.88
bash-4.4# 
```
`magic-wormhole-mailbox`:
```
$ docker run -it --rm nebulaworks/magic-wormhole-mailbox:msahb86b470r5636v8imzs8sghgzg38b
2021-07-28T16:29:55+0000 [-] RLIMIT_NOFILE.soft was 1048576, leaving it alone
2021-07-28T16:29:55+0000 [-] populating new database with schema channel v1
2021-07-28T16:29:55+0000 [-] populating new database with schema usage v2
2021-07-28T16:29:55+0000 [-] not blurring access times
2021-07-28T16:29:55+0000 [-] websocket listening on ws://HOSTNAME:PORT/v1
2021-07-28T16:29:55+0000 [-] Wormhole relay server running
2021-07-28T16:29:55+0000 [-] not blurring access times
2021-07-28T16:29:55+0000 [-] beginning app prune
2021-07-28T16:29:55+0000 [-] app prune ends, 0 apps
2021-07-28T16:29:55+0000 [-] PrivacyEnhancedSite starting on 4000
2021-07-28T16:29:55+0000 [wormhole_mailbox_server.web.PrivacyEnhancedSite#info] Starting factory <wormhole_mailbox_server.web.PrivacyEnhancedSite object at 0x7f2645010bd0>
2021-07-28T16:29:55+0000 [twisted.application.runner._runner.Runner#info] Starting reactor...
```

`pki-validator`:
```
~ $ docker-run nebulaworks/pki-validator:h13qqs6wwmkz9g5hb9ca9hnyzchsp2al /bin/bash
Unable to find image 'nebulaworks/pki-validator:h13qqs6wwmkz9g5hb9ca9hnyzchsp2al' locally
h13qqs6wwmkz9g5hb9ca9hnyzchsp2al: Pulling from nebulaworks/pki-validator
c3e8a5b57b24: Pull complete 
Digest: sha256:87d9c80b217bfbbc508cfd60532a319db548d1e81e5b2c5d317adb6ad0829097
Status: Downloaded newer image for nebulaworks/pki-validator:h13qqs6wwmkz9g5hb9ca9hnyzchsp2al
bash-4.4# openssl
OpenSSL> quit
bash-4.4# make
make: *** No targets specified and no makefile found.  Stop.
bash-4.4# 
```

**Review by jshcmpbll — APPROVED** [review]
LGTM!

**Pull request merged**
