### PR TITLE
[READY] Testing out actions and doc updates

### PR DESCRIPTION
**Pull request by sarcasticadmin**
## Description

* Testing out the github actions from #8 
* Updates to the publishing docs to account for new comment functionality in GHA

### CODE REVIEW

**Comment by sarcasticadmin** [comment]
publish

**Comment by nwi-auto** [comment]
The following docker images: 
awsutils, helmsman-aws
have been published on [Docker Hub](https://hub.docker.com/u/nebulaworks).

**Comment by sarcasticadmin** [comment]
@Nebulaworks/approvers this is ready to go

**Comment by maishiroma** [comment]
@sarcasticadmin Looks good on my end! Thanks for writing up the process on how to publish these docker images using the new process!

**Pull request merged**
