### PR TITLE
[WIP] do/issue-345: cachix readme and use in nix img build/publish

### PR DESCRIPTION
**Pull request by davido-nw**
## Description of PR
Caching nix binaries is a good thing. Let's do this.

## Tests
- CI passes (it won't yet because the secret needs to be added to the repo settings).

### CODE REVIEW

**Comment by davido-nw** [comment]
publish images

**Comment by nwi-auto** [comment]
The following docker images: 
awsutils, helmsman-aws, magic-wormhole-mailbox, pki-validator
have been published on [Docker Hub](https://hub.docker.com/u/nebulaworks).

**Comment by davido-nw** [comment]
publish images

**Comment by nwi-auto** [comment]
The following docker images: 
awsutils, helmsman-aws, magic-wormhole-mailbox, pki-validator
have been published on [Docker Hub](https://hub.docker.com/u/nebulaworks).

**Comment by davido-nw** [comment]
Closing this in favor of https://github.com/Nebulaworks/nix-garage/pull/29.

**Pull request closed without merging**
